- hosts: testserver
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: playbooks/packages.yml
    - include: playbooks/users.yml
